// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpI7QCZ0ZHC5ycUHHhTPkM8c8ykJA1HXs',
    appId: '1:32597198597:web:46e6030111e9a75d43996c',
    messagingSenderId: '32597198597',
    projectId: 'checklist-app-39f0d',
    authDomain: 'checklist-app-39f0d.firebaseapp.com',
    storageBucket: 'checklist-app-39f0d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACbPQQrkdS8xP_O9AvWr87fO162AJ-zyY',
    appId: '1:32597198597:android:2b9065d7322380a343996c',
    messagingSenderId: '32597198597',
    projectId: 'checklist-app-39f0d',
    storageBucket: 'checklist-app-39f0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3KXYffOqPbnCjggLrydGUlO_hbZM0C1o',
    appId: '1:32597198597:ios:df070a7dcbc1626043996c',
    messagingSenderId: '32597198597',
    projectId: 'checklist-app-39f0d',
    storageBucket: 'checklist-app-39f0d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3KXYffOqPbnCjggLrydGUlO_hbZM0C1o',
    appId: '1:32597198597:ios:df070a7dcbc1626043996c',
    messagingSenderId: '32597198597',
    projectId: 'checklist-app-39f0d',
    storageBucket: 'checklist-app-39f0d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpI7QCZ0ZHC5ycUHHhTPkM8c8ykJA1HXs',
    appId: '1:32597198597:web:fb5ead1998ee62c043996c',
    messagingSenderId: '32597198597',
    projectId: 'checklist-app-39f0d',
    authDomain: 'checklist-app-39f0d.firebaseapp.com',
    storageBucket: 'checklist-app-39f0d.firebasestorage.app',
  );

}